### ISSUE TITLE
Authors?

### ISSUE THREAD

**Issue by mem48** [saferactive/rrsrr#32]
@Robinlovelace just checking, but some of the text in the book is stuff I wrote for the Transport Data Science course. So can you cite or add me as an author for that section?

**Comment by Robinlovelace** [comment]
Hi @mem48, sure, PRs are welcome. I gave heads-up on the change here, did you not see that?: https://github.com/ITSLeeds/rrsrr/commit/83c4c9bfcf6e5589c78d8522f351b627db2bf092#commitcomment-43296715

I think the section that has most input from you is this one although even that has has changed substantially since the original with way more text that previously https://docs.ropensci.org/stats19/articles/stats19-training.html#manipulating-r-objects-1 ( the smily face at the end is unchanged though : ) https://itsleeds.github.io/rrsrr/basics.html
